version: '3.9'

services:
  server1:
    container_name: server_1
    build: .
    restart: on-failure
    ports: 
      - "8080:8080"
    depends_on:
      - db
  # server2:
  #   build: .
  #   restart: on-failure
  #   ports: 
  #     - "8082:8080"
  #   depends_on:
  #     - db
  db:
    container_name: database
    image: 'postgres:15.4'
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: 'uniexplorers'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data
  
  seed_migration:
    container_name: seed_migration
    build:
      context: .
    links:
      - db
    depends_on:
      - db
    command: /bin/sh -c /app/migrate.sh
  
  ingestion:
    container_name: ingestion
    build: ./populate_db
    depends_on:
      - db
      - seed_migration
    command: python ingest.py  # assuming your script is named ingest.py
  # nginx:
  #   build: ./nginx
  #   ports:
  #   - '8080:8080'
volumes:
  data: