version: '3.9'

services:
  server1:
    container_name: server_1
    build: .
    restart: on-failure
    ports: 
      - "8080:8080"
    depends_on:
      - db
  # server2:
  #   build: .
  #   restart: on-failure
  #   ports: 
  #     - "8082:8080"
  #   depends_on:
  #     - db
  db:
    container_name: database
    image: 'postgres:15.4'
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: 'uniexplorers'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  seed_migration:
    container_name: seed_migration
    build:
      context: .
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx knex migrate:latest && npx knex seed:run"
  
  ingestion:
    container_name: ingestion
    build: ./populate_db
    depends_on:
      db:
        condition: service_healthy
    command: python ingest.py  # assuming your script is named ingest.py
  # nginx:
  #   build: ./nginx
  #   ports:
  #   - '8080:8080'
volumes:
  data: